In [1]:
library(microDecon)
library(tidyverse)
library(phyloseq)
library(readxl)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
extraction_batches_raw <- readxl::read_xlsx("Extraction Batches.xlsx")

New names:
• `` -> `...5`

In [3]:
extraction_batches <- dplyr::mutate(extraction_batches_raw,
                              sequenced_tag = if_else(lab_blank %in% Not_sequenced, "Not_sequenced", "Sequenced"),
                              lab_blank = if_else(lab_blank %in% Not_sequenced, NA_character_, lab_blank),
                              date = as.Date(date, format = "%d/%m/%Y"),
                              #Set date as NA if thata is not sequenced to ensure correct batch assignment
                              assigned_date = if_else(sequenced_tag == "Not_sequenced", NA, date)) |>
                              #This assigns 
                              tidyr::fill(assigned_date, lab_blank) |>
                       dplyr::group_by(assigned_date, lab_blank, field_blank) |>
                       dplyr::mutate(batch = paste0("Batch_", dplyr::cur_group_id())) |>
                       dplyr::ungroup() |>
                       dplyr::mutate(batch = factor(batch, levels = sort(unique(batch)))) |>
                       dplyr::rename(field_sample = sample_id) |>
                       dplyr::select(batch, date, assigned_date, field_sample, lab_blank, field_blank, sequenced_tag)

In [4]:
sample_n(extraction_batches, 5)

  batch    date       assigned_date field_sample lab_blank field_blank
1 Batch_7  2026-05-12 2026-05-12    T3IS3        T3ISL3    NA
2 Batch_8  2026-05-13 2026-05-13    T2SS2        T2SSL2    NA
3 Batch_4  2026-05-08 2026-05-08    T3SG3        T3SGL3    NA
4 Batch_10 2026-05-14 2026-05-14    T3W1         T3L3      T3WB
5 Batch_1  2026-05-07 2026-05-07    T1W2         T1L1      T1WB
  sequenced_tag
1 Sequenced
2 Sequenced
3 Sequenced
4 Sequenced
5 Sequenced

In [5]:
extraction_batches_all <- extraction_batches |>
                          tidyr::pivot_longer(cols = c(field_sample, lab_blank, field_blank), names_to = "source", values_to = "sample_id") |>
                          dplyr::filter(!is.na(sample_id)) |>
                          dplyr::mutate(sample_id = dplyr::recode(sample_id, "T3SGL3" = "T3SGL")) |>
                          dplyr::distinct(sample_id, source, .keep_all = TRUE)

sample_n(extraction_batches_all, size = 5)
dim(extraction_batches_all)

  batch    date       assigned_date sequenced_tag source       sample_id
1 Batch_9  2026-05-13 2026-05-13    Sequenced     lab_blank    T3SSL3
2 Batch_5  2026-05-09 2026-05-09    Sequenced     field_sample T2W2
3 Batch_4  2026-05-08 2026-05-08    Sequenced     field_sample T3SG1
4 Batch_10 2026-05-14 2026-05-14    Sequenced     field_blank  T3WB
5 Batch_8  2026-05-13 2026-05-13    Sequenced     lab_blank    T2SSL2

[1] 53  6

In [6]:
(phyloseq_16S <- read_rds("16S_phyloseq.rds"))

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 17269 taxa and 53 samples ]
sample_data() Sample Data:       [ 53 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 17269 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 17269 tips and 17253 internal nodes ]

In [7]:
(temp_sample_data <- data.frame(sample_data(phyloseq_16S)) |>
                     tibble::rownames_to_column(var = "Read_tag") |>
                     dplyr::rename(sample_id = sample)) |>  sample_n(size = 5)
dim(temp_sample_data)

  Read_tag                               transect habitat
1 RemovePrimer_Final.T1IS1_8522605005578 T1       intertidal_saltmarsh
2 RemovePrimer_Final.T2SS1_8522605005590 T2       supratidal_saltmarsh
3 RemovePrimer_Final.T3SG2_8522605005575 T3       seagrass
4 RemovePrimer_Final.T2W2_8522605005559  T2       water
5 RemovePrimer_Final.T2IS3_8522605005583 T2       intertidal_saltmarsh
  microbial_community sample_id plant_species_1      plant_species_2
1 prokaryote          T1IS1     Salicornia_tegataria Triglochin_striata
2 prokaryote          T2SS1     Salicornia_pilansii  Canolia_diffusa
3 prokaryote          T3SG2     zostera_capensis     zostera_capensis
4 prokaryote          T2W2      NA                   NA
5 prokaryote          T2IS3     Salicornia_tegataria Triglochin_striata
  blank_group
1 Real Sample
2 Real Sample
3 Real Sample
4 Real Sample
5 Real Sample

[1] 53  8

In [8]:
colnames(temp_sample_data)

[1] "Read_tag"            "transect"            "habitat"
[4] "microbial_community" "sample_id"           "plant_species_1"
[7] "plant_species_2"     "blank_group"

In [9]:
`%nin%` <- Negate(`%in%`)

In [10]:
dplyr::filter(extraction_batches_all, str_detect(sample_id, "T3SG"))

  batch    date       assigned_date sequenced_tag source       sample_id
1 Batch_4  2026-05-08 2026-05-08    Sequenced     field_sample T3SG1
2 Batch_4  2026-05-08 2026-05-08    Sequenced     lab_blank    T3SGL
3 Batch_4  2026-05-08 2026-05-08    Sequenced     field_sample T3SG2
4 Batch_4  2026-05-08 2026-05-08    Sequenced     field_sample T3SG3
5 Batch_11 2026-05-14 2026-05-14    Sequenced     field_sample T3SGB

In [11]:
#extraction_batches_all$sample_id
temp_sample_data[temp_sample_data$sample_id  %nin% extraction_batches_all$sample_id,]

     Read_tag transect habitat microbial_community sample_id plant_species_1
     plant_species_2 blank_group

In [12]:
head(temp_sample_data, 3)

  Read_tag                               transect habitat
1 RemovePrimer_Final.T1IS1_8522605005578 T1       intertidal_saltmarsh
2 RemovePrimer_Final.T1IS2_8522605005579 T1       intertidal_saltmarsh
3 RemovePrimer_Final.T1IS3_8522605005580 T1       intertidal_saltmarsh
  microbial_community sample_id plant_species_1      plant_species_2
1 prokaryote          T1IS1     Salicornia_tegataria Triglochin_striata
2 prokaryote          T1IS2     Salicornia_tegataria Triglochin_striata
3 prokaryote          T1IS3     Salicornia_tegataria Triglochin_striata
  blank_group
1 Real Sample
2 Real Sample
3 Real Sample

In [13]:
extraction_batches_merged <- merge(temp_sample_data, extraction_batches_all)

In [14]:
dput(unique(extraction_batches_merged$habitat))

c("intertidal_saltmarsh", "lab", "seagrass", "seagrass_bare",
"supratidal_saltmarsh", "water", "field_blank")

In [15]:
#add levels according to microdecontam: blanks first
extraction_batches_merged$source <- factor(extraction_batches_merged$source, levels = c("lab_blank", "field_blank", "field_sample"))
extraction_batches_merged$habitat <- factor(extraction_batches_merged$habitat, levels = c("lab", "field_blank", "water", "seagrass_bare", "seagrass", "intertidal_saltmarsh", "supratidal_saltmarsh"))
#Arrange sample_id by first by date, and then by source and then by sample id
(extraction_batches_merged <- dplyr::arrange(extraction_batches_merged, date, source, sample_id, habitat))

   sample_id Read_tag                                transect
1  T1L1      RemovePrimer_Final.T1L1_8522605005596   T0
2  T1SGL1    RemovePrimer_Final.T1SGL1_8522605005599 T0
3  T1WB      RemovePrimer_Final.T1WB_8522605005557   T1
4  T1SG1     RemovePrimer_Final.T1SG1_8522605005566  T1
5  T1SG2     RemovePrimer_Final.T1SG2_8522605005567  T1
6  T1SG3     RemovePrimer_Final.T1SG3_8522605005568  T1
7  T1W1      RemovePrimer_Final.T1W1_8522605005554   T1
8  T1W2      RemovePrimer_Final.T1W2_8522605005555   T1
9  T1W3      RemovePrimer_Final.T1W3_8522605005556   T1
10 T1ISL1    RemovePrimer_Final.T1ISL1_8522605005601 T0
11 T3SGL     RemovePrimer_Final.T3SGL3_8522605005600 T0
12 T1IS1     RemovePrimer_Final.T1IS1_8522605005578  T1
13 T1IS2     RemovePrimer_Final.T1IS2_8522605005579  T1
14 T1IS3     RemovePrimer_Final.T1IS3_8522605005580  T1
15 T2SG1     RemovePrimer_Final.T2SG1_8522605005570  T2
16 T2SG2     RemovePrimer_Final.T2SG2_8522605005571  T2
17 T2SG3     RemovePrimer_Final.T2SG3_8522605005572  T2
18 T3SG1     RemovePrimer_Final.T3SG1_8522605005574  T3
19 T3SG2     RemovePrimer_Final.T3SG2_8522605005575  T3
20 T3SG3     RemovePrimer_Final.T3SG3_8522605005576  T3
21 T2L2      RemovePrimer_Final.T2L2_8522605005597   T0
22 T2WB      RemovePrimer_Final.T2WB_8522605005561   T2
23 T2IS1     RemovePrimer_Final.T2IS1_8522605005581  T2
24 T2IS2     RemovePrimer_Final.T2IS2_8522605005582  T2
25 T2IS3     RemovePrimer_Final.T2IS3_8522605005583  T2
26 T2W1      RemovePrimer_Final.T2W1_8522605005558   T2
27 T2W2      RemovePrimer_Final.T2W2_8522605005559   T2
28 T2W3      RemovePrimer_Final.T2W3_8522605005560   T2
29 T1SSL1    RemovePrimer_Final.T1SSL1_8522605005603 T0
30 T3ISL3    RemovePrimer_Final.T3ISL3_8522605005602 T0
31 T1SS1     RemovePrimer_Final.T1SS1_8522605005587  T1
32 T1SS2     RemovePrimer_Final.T1SS2_8522605005588  T1
33 T1SS3     RemovePrimer_Final.T1SS3_8522605005589  T1
34 T3IS1     RemovePrimer_Final.T3IS1_8522605005584  T3
35 T3IS2     RemovePrimer_Final.T3IS2_8522605005585  T3
36 T3IS3     RemovePrimer_Final.T3IS3_8522605005586  T3
37 T2SSL2    RemovePrimer_Final.T2SSL2_8522605005604 T0
38 T3SSL3    RemovePrimer_Final.T3SSL3_8522605005605 T0
39 T2SS1     RemovePrimer_Final.T2SS1_8522605005590  T2
40 T2SS2     RemovePrimer_Final.T2SS2_8522605005591  T2
41 T2SS3     RemovePrimer_Final.T2SS3_8522605005592  T2
42 T3SS1     RemovePrimer_Final.T3SS1_8522605005593  T3
43 T3SS2     RemovePrimer_Final.T3SS2_8522605005594  T3
44 T3SS3     RemovePrimer_Final.T3SS3_8522605005595  T3
45 T3L3      RemovePrimer_Final.T3L3_8522605005598   T3
46 TSGBL1    RemovePrimer_Final.TSGBL1_8522605005606 T0
47 T3WB      RemovePrimer_Final.T3WB_8522605005565   T3
48 T1SGB     RemovePrimer_Final.T1SGB_8522605005569  T1
49 T2SGB     RemovePrimer_Final.T2SGB_8522605005573  T2
50 T3SGB     RemovePrimer_Final.T3SGB_8522605005577  T3
51 T3W1      RemovePrimer_Final.T3W1_8522605005562   T3
52 T3W2      RemovePrimer_Final.T3W2_8522605005563   T3
53 T3W3      RemovePrimer_Final.T3W3_8522605005564   T3
   habitat              microbial_community plant_species_1
1  lab                  prokaryote          NA
2  lab                  prokaryote          zostera_capensis
3  field_blank          prokaryote          NA
4  seagrass             prokaryote          zostera_capensis
5  seagrass             prokaryote          zostera_capensis
6  seagrass             prokaryote          zostera_capensis
7  water                prokaryote          NA
8  water                prokaryote          NA
9  water                prokaryote          NA
10 lab                  prokaryote          Salicornia_tegataria
11 lab                  prokaryote          zostera_capensis
12 intertidal_saltmarsh prokaryote          Salicornia_tegataria
13 intertidal_saltmarsh prokaryote          Salicornia_tegataria
14 intertidal_saltmarsh prokaryote          Salicornia_tegataria
15 seagrass             prokaryote          zostera_capensis
16 seagrass             prokaryote          zostera_capensis
17 seagrass             prokaryote          zostera_capensis
18 seagrass             prokaryote          zostera_capensis
19 seagrass             prokaryote          zostera_capensis
20 seagrass             prokaryote          zostera_capensis
21 lab                  prokaryote          NA
22 field_blank          prokaryote          NA
23 intertidal_saltmarsh prokaryote          Salicornia_tegataria
24 intertidal_saltmarsh prokaryote          Salicornia_tegataria
25 intertidal_saltmarsh prokaryote          Salicornia_tegataria
26 water                prokaryote          NA
27 water                prokaryote          NA
28 water                prokaryote          NA
29 lab                  prokaryote          Salicornia_pilansii
30 lab                  prokaryote          Salicornia_tegataria
31 supratidal_saltmarsh prokaryote          Salicornia_pilansii
32 supratidal_saltmarsh prokaryote          Salicornia_pilansii
33 supratidal_saltmarsh prokaryote          Salicornia_pilansii
34 intertidal_saltmarsh prokaryote          Salicornia_tegataria
35 intertidal_saltmarsh prokaryote          Salicornia_tegataria
36 intertidal_saltmarsh prokaryote          Salicornia_tegataria
37 lab                  prokaryote          Salicornia_pilansii
38 lab                  prokaryote          Salicornia_pilansii
39 supratidal_saltmarsh prokaryote          Salicornia_pilansii
40 supratidal_saltmarsh prokaryote          Salicornia_pilansii
41 supratidal_saltmarsh prokaryote          Salicornia_pilansii
42 supratidal_saltmarsh prokaryote          Salicornia_pilansii
43 supratidal_saltmarsh prokaryote          Salicornia_pilansii
44 supratidal_saltmarsh prokaryote          Salicornia_pilansii
45 lab                  prokaryote          NA
46 lab                  prokaryote          zostera_capensis
47 field_blank          prokaryote          NA
48 seagrass_bare        prokaryote          zostera_capensis
49 seagrass_bare        prokaryote          zostera_capensis
50 seagrass_bare        prokaryote          zostera_capensis
51 water                prokaryote          NA
52 water                prokaryote          NA
53 water                prokaryote          NA
   plant_species_2    blank_group batch    date       assigned_date
1  NA                 Real Sample Batch_1  2026-05-07 2026-05-07
2  zostera_capensis   Real Sample Batch_2  2026-05-07 2026-05-07
3  NA                 Field Blank Batch_1  2026-05-07 2026-05-07
4  zostera_capensis   Real Sample Batch_2  2026-05-07 2026-05-07
5  zostera_capensis   Real Sample Batch_2  2026-05-07 2026-05-07
6  zostera_capensis   Real Sample Batch_2  2026-05-07 2026-05-07
7  NA                 Real Sample Batch_1  2026-05-07 2026-05-07
8  NA                 Real Sample Batch_1  2026-05-07 2026-05-07
9  NA                 Real Sample Batch_1  2026-05-07 2026-05-07
10 Triglochin_striata Real Sample Batch_3  2026-05-08 2026-05-08
11 zostera_capensis   Real Sample Batch_4  2026-05-08 2026-05-08
12 Triglochin_striata Real Sample Batch_3  2026-05-08 2026-05-08
13 Triglochin_striata Real Sample Batch_3  2026-05-08 2026-05-08
14 Triglochin_striata Real Sample Batch_3  2026-05-08 2026-05-08
15 zostera_capensis   Real Sample Batch_2  2026-05-08 2026-05-07
16 zostera_capensis   Real Sample Batch_2  2026-05-08 2026-05-07
17 zostera_capensis   Real Sample Batch_2  2026-05-08 2026-05-07
18 zostera_capensis   Real Sample Batch_4  2026-05-08 2026-05-08
19 zostera_capensis   Real Sample Batch_4  2026-05-08 2026-05-08
20 zostera_capensis   Real Sample Batch_4  2026-05-08 2026-05-08
21 NA                 Real Sample Batch_5  2026-05-09 2026-05-09
22 NA                 Field Blank Batch_5  2026-05-09 2026-05-09
23 Triglochin_striata Real Sample Batch_3  2026-05-09 2026-05-08
24 Triglochin_striata Real Sample Batch_3  2026-05-09 2026-05-08
25 Triglochin_striata Real Sample Batch_3  2026-05-09 2026-05-08
26 NA                 Real Sample Batch_5  2026-05-09 2026-05-09
27 NA                 Real Sample Batch_5  2026-05-09 2026-05-09
28 NA                 Real Sample Batch_5  2026-05-09 2026-05-09
29 Canolia_diffusa    Real Sample Batch_6  2026-05-12 2026-05-12
30 Triglochin_striata Real Sample Batch_7  2026-05-12 2026-05-12
31 Canolia_diffusa    Real Sample Batch_6  2026-05-12 2026-05-12
32 Canolia_diffusa    Real Sample Batch_6  2026-05-12 2026-05-12
33 Canolia_diffusa    Real Sample Batch_6  2026-05-12 2026-05-12
34 Triglochin_striata Real Sample Batch_7  2026-05-12 2026-05-12
35 Triglochin_striata Real Sample Batch_7  2026-05-12 2026-05-12
36 Triglochin_striata Real Sample Batch_7  2026-05-12 2026-05-12
37 Canolia_diffusa    Real Sample Batch_8  2026-05-13 2026-05-13
38 Canolia_diffusa    Real Sample Batch_9  2026-05-13 2026-05-13
39 Canolia_diffusa    Real Sample Batch_8  2026-05-13 2026-05-13
40 Canolia_diffusa    Real Sample Batch_8  2026-05-13 2026-05-13
41 Canolia_diffusa    Real Sample Batch_8  2026-05-13 2026-05-13
42 Canolia_diffusa    Real Sample Batch_9  2026-05-13 2026-05-13
43 Canolia_diffusa    Real Sample Batch_9  2026-05-13 2026-05-13
44 Canolia_diffusa    Real Sample Batch_9  2026-05-13 2026-05-13
45 NA                 Real Sample Batch_10 2026-05-14 2026-05-14
46 zostera_capensis   Real Sample Batch_11 2026-05-14 2026-05-14
47 NA                 Field Blank Batch_10 2026-05-14 2026-05-14
48 zostera_capensis   Real Sample Batch_11 2026-05-14 2026-05-14
49 zostera_capensis   Real Sample Batch_11 2026-05-14 2026-05-14
50 zostera_capensis   Real Sample Batch_11 2026-05-14 2026-05-14
51 NA                 Real Sample Batch_10 2026-05-14 2026-05-14
52 NA                 Real Sample Batch_10 2026-05-14 2026-05-14
53 NA                 Real Sample Batch_10 2026-05-14 2026-05-14
   sequenced_tag source
1  Sequenced     lab_blank
2  Sequenced     lab_blank
3  Sequenced     field_blank
4  Sequenced     field_sample
5  Sequenced     field_sample
6  Sequenced     field_sample
7  Sequenced     field_sample
8  Sequenced     field_sample
9  Sequenced     field_sample
10 Sequenced     lab_blank
11 Sequenced     lab_blank
12 Sequenced     field_sample
13 Sequenced     field_sample
14 Sequenced     field_sample
15 Not_sequenced field_sample
16 Not_sequenced field_sample
17 Not_sequenced field_sample
18 Sequenced     field_sample
19 Sequenced     field_sample
20 Sequenced     field_sample
21 Sequenced     lab_blank
22 Sequenced     field_blank
23 Not_sequenced field_sample
24 Not_sequenced field_sample
25 Not_sequenced field_sample
26 Sequenced     field_sample
27 Sequenced     field_sample
28 Sequenced     field_sample
29 Sequenced     lab_blank
30 Sequenced     lab_blank
31 Sequenced     field_sample
32 Sequenced     field_sample
33 Sequenced     field_sample
34 Sequenced     field_sample
35 Sequenced     field_sample
36 Sequenced     field_sample
37 Sequenced     lab_blank
38 Sequenced     lab_blank
39 Sequenced     field_sample
40 Sequenced     field_sample
41 Sequenced     field_sample
42 Sequenced     field_sample
43 Sequenced     field_sample
44 Sequenced     field_sample
45 Sequenced     lab_blank
46 Sequenced     lab_blank
47 Sequenced     field_blank
48 Sequenced     field_sample
49 Sequenced     field_sample
50 Sequenced     field_sample
51 Sequenced     field_sample
52 Sequenced     field_sample
53 Sequenced     field_sample

In [16]:
#Test to check order as MicroDecon expects blanks first
extraction_batch <- extraction_batches_merged |> dplyr::filter(batch == "Batch_2")

In [17]:
extraction_batch

  sample_id Read_tag                                transect habitat
1 T1SGL1    RemovePrimer_Final.T1SGL1_8522605005599 T0       lab
2 T1SG1     RemovePrimer_Final.T1SG1_8522605005566  T1       seagrass
3 T1SG2     RemovePrimer_Final.T1SG2_8522605005567  T1       seagrass
4 T1SG3     RemovePrimer_Final.T1SG3_8522605005568  T1       seagrass
5 T2SG1     RemovePrimer_Final.T2SG1_8522605005570  T2       seagrass
6 T2SG2     RemovePrimer_Final.T2SG2_8522605005571  T2       seagrass
7 T2SG3     RemovePrimer_Final.T2SG3_8522605005572  T2       seagrass
  microbial_community plant_species_1  plant_species_2  blank_group batch
1 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
2 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
3 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
4 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
5 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
6 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
7 prokaryote          zostera_capensis zostera_capensis Real Sample Batch_2
  date       assigned_date sequenced_tag source
1 2026-05-07 2026-05-07    Sequenced     lab_blank
2 2026-05-07 2026-05-07    Sequenced     field_sample
3 2026-05-07 2026-05-07    Sequenced     field_sample
4 2026-05-07 2026-05-07    Sequenced     field_sample
5 2026-05-08 2026-05-07    Not_sequenced field_sample
6 2026-05-08 2026-05-07    Not_sequenced field_sample
7 2026-05-08 2026-05-07    Not_sequenced field_sample

In [18]:
last_field_blank_index <- tail(which(as.character(extraction_batch$source) == "field_blank"), 1)
last_labblank_index <- tail(which(as.character(extraction_batch$source) == "lab_blank"), 1)
(numb.blanks <- max(last_field_blank_index, last_labblank_index))

[1] 1

In [19]:
xtabs(~habitat, data = extraction_batch)

habitat
                 lab          field_blank                water
                   1                    0                    0
       seagrass_bare             seagrass intertidal_saltmarsh
                   0                    6                    0
supratidal_saltmarsh
                   0

In [20]:
(numb.ind <- dput(dplyr::filter(extraction_batch, habitat %nin% c("lab", "field_blank")) |>
             dplyr::count(habitat) |> 
             dplyr::pull(n)))

6L

[1] 6

In [21]:
#sanity check
stopifnot(dim(extraction_batch)[1] == numb.blanks + sum(numb.ind))

In [25]:
#extraction_batch

In [23]:
decontaminated_test <- decon(data = extraction_batch ,numb.blanks = numb.blanks, numb.ind = numb.ind,taxa = F)

ERROR: Error in decon(data = extraction_batch, numb.blanks = numb.blanks, numb.ind = numb.ind, : Total number of input columns does not match the number of columns in 'data.' Check that an OTU ID column is present, the number of blanks (numb.blanks) and number of individuals (numb.ind) are entered correctly, and the taxa column is correctly specified as present or absent

In [ ]:
#head(temp_sample_data)

In [ ]:
lapply(unique(extraction_batches_all$batch), function(current_batch) {
    
      extraction_batch <- extraction_batches_all |> dplyr::filter(batch == current_batch)
      last_field_blank_index <- tail(which(as.character(extraction_batch$source) == "field_blank"), 1)
      last_labblank_index <- tail(which(as.character(extraction_batch$source) == "lab_blank"), 1)
      (numb.blanks <- max(last_field_blank_index, last_labblank_index))
    
      batch_decon <- decon(data = extraction_batch, numb.blanks = numb.blanks, numb.ind = numb.ind,taxa = F)
        
})

In [ ]:
example <- cbind.data.frame(c("OTU1","OTU2","OTU3","OTU4","OTU5","OTU6"),
                        c(0,200,1000,50,0,25),
                        c(0,220,800,30,0,10),
                        c(0,180,1300,70,0,30),
                        c(60,660,1440,70,2400,30),
                        c(64,520,1000,48,1900,20),
                        c(40,480,700,35,2100,15),
                        c("K_Bacteria; P_Actinobacteria","K_Bacteria; P_Proteobacteria","K_Bacteria; P_Proteobacteria","K_Bacteria; P_Bacteroidetes","K_Bacteria","K_Bacteria"))
colnames(example) <- c("OTU_ID","Blank1","Blank2","Blank3","Pop1_Sample1","Pop1_Sample2","Pop2_Sample3","Taxa")

In [ ]:
example

In [ ]:
decontaminated <- decon(data = example,numb.blanks=3, numb.ind=c(2,1),taxa=T)