In [2]:
library(tidyverse)
library(phyloseq)
library(readxl)

In [3]:
extraction_batches_raw <- readxl::read_xlsx("Extraction Batches.xlsx")

New names:
• `` -> `...5`

In [60]:
extraction_batches <- dplyr::mutate(extraction_batches_raw,
                              sequenced_tag = if_else(lab_blank %in% Not_sequenced, "Not_sequenced", "Sequenced"),
                              lab_blank = if_else(lab_blank %in% Not_sequenced, NA_character_, lab_blank),
                              date = as.Date(date, format = "%d/%m/%Y"),
                              #Set date as NA if thata is not sequenced to ensure correct batch assignment
                              assigned_date = if_else(sequenced_tag == "Not_sequenced", NA, date)) |>
                              #This assigns 
                              tidyr::fill(assigned_date, lab_blank) |>
                       dplyr::group_by(assigned_date, lab_blank, field_blank) |>
                       dplyr::mutate(batch = paste0("Batch_", dplyr::cur_group_id())) |>
                       dplyr::ungroup() |>
                       dplyr::mutate(batch = factor(batch, levels = sort(unique(batch)))) |>
                       dplyr::select(batch, date, assigned_date, sample_id, lab_blank, field_blank, sequenced_tag)

In [61]:
extraction_batches

   batch    date       assigned_date sample_id lab_blank field_blank
1  Batch_1  2026-05-07 2026-05-07    T1W1      T1L1      T1WB
2  Batch_1  2026-05-07 2026-05-07    T1W2      T1L1      T1WB
3  Batch_1  2026-05-07 2026-05-07    T1W3      T1L1      T1WB
4  Batch_2  2026-05-07 2026-05-07    T1SG1     T1SGL1    NA
5  Batch_2  2026-05-07 2026-05-07    T1SG2     T1SGL1    NA
6  Batch_2  2026-05-07 2026-05-07    T1SG3     T1SGL1    NA
7  Batch_2  2026-05-08 2026-05-07    T2SG1     T1SGL1    NA
8  Batch_2  2026-05-08 2026-05-07    T2SG2     T1SGL1    NA
9  Batch_2  2026-05-08 2026-05-07    T2SG3     T1SGL1    NA
10 Batch_4  2026-05-08 2026-05-08    T3SG1     T3SGL3    NA
11 Batch_4  2026-05-08 2026-05-08    T3SG2     T3SGL3    NA
12 Batch_4  2026-05-08 2026-05-08    T3SG3     T3SGL3    NA
13 Batch_3  2026-05-08 2026-05-08    T1IS1     T1ISL1    NA
14 Batch_3  2026-05-08 2026-05-08    T1IS2     T1ISL1    NA
15 Batch_3  2026-05-08 2026-05-08    T1IS3     T1ISL1    NA
16 Batch_3  2026-05-09 2026-05-08    T2IS1     T1ISL1    NA
17 Batch_3  2026-05-09 2026-05-08    T2IS2     T1ISL1    NA
18 Batch_3  2026-05-09 2026-05-08    T2IS3     T1ISL1    NA
19 Batch_5  2026-05-09 2026-05-09    T2W1      T2L2      T2WB
20 Batch_5  2026-05-09 2026-05-09    T2W2      T2L2      T2WB
21 Batch_5  2026-05-09 2026-05-09    T2W3      T2L2      T2WB
22 Batch_7  2026-05-12 2026-05-12    T3IS1     T3ISL3    NA
23 Batch_7  2026-05-12 2026-05-12    T3IS2     T3ISL3    NA
24 Batch_7  2026-05-12 2026-05-12    T3IS3     T3ISL3    NA
25 Batch_6  2026-05-12 2026-05-12    T1SS1     T1SSL1    NA
26 Batch_6  2026-05-12 2026-05-12    T1SS2     T1SSL1    NA
27 Batch_6  2026-05-12 2026-05-12    T1SS3     T1SSL1    NA
28 Batch_8  2026-05-13 2026-05-13    T2SS1     T2SSL2    NA
29 Batch_8  2026-05-13 2026-05-13    T2SS2     T2SSL2    NA
30 Batch_8  2026-05-13 2026-05-13    T2SS3     T2SSL2    NA
31 Batch_9  2026-05-13 2026-05-13    T3SS1     T3SSL3    NA
32 Batch_9  2026-05-13 2026-05-13    T3SS2     T3SSL3    NA
33 Batch_9  2026-05-13 2026-05-13    T3SS3     T3SSL3    NA
34 Batch_10 2026-05-14 2026-05-14    T3W1      T3L3      T3WB
35 Batch_10 2026-05-14 2026-05-14    T3W2      T3L3      T3WB
36 Batch_10 2026-05-14 2026-05-14    T3W3      T3L3      T3WB
37 Batch_11 2026-05-14 2026-05-14    T1SGB     TSGBL1    NA
38 Batch_11 2026-05-14 2026-05-14    T2SGB     TSGBL1    NA
39 Batch_11 2026-05-14 2026-05-14    T3SGB     TSGBL1    NA
   sequenced_tag
1  Sequenced
2  Sequenced
3  Sequenced
4  Sequenced
5  Sequenced
6  Sequenced
7  Not_sequenced
8  Not_sequenced
9  Not_sequenced
10 Sequenced
11 Sequenced
12 Sequenced
13 Sequenced
14 Sequenced
15 Sequenced
16 Not_sequenced
17 Not_sequenced
18 Not_sequenced
19 Sequenced
20 Sequenced
21 Sequenced
22 Sequenced
23 Sequenced
24 Sequenced
25 Sequenced
26 Sequenced
27 Sequenced
28 Sequenced
29 Sequenced
30 Sequenced
31 Sequenced
32 Sequenced
33 Sequenced
34 Sequenced
35 Sequenced
36 Sequenced
37 Sequenced
38 Sequenced
39 Sequenced

In [6]:
(phyloseq_16S <- read_rds("16S_phyloseq.rds"))

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 17269 taxa and 53 samples ]
sample_data() Sample Data:       [ 53 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 17269 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 17269 tips and 17253 internal nodes ]

In [46]:
sample_data(phyloseq_16S) |> head(3)

                                       transect habitat
RemovePrimer_Final.T1IS1_8522605005578 T1       intertidal_saltmarsh
RemovePrimer_Final.T1IS2_8522605005579 T1       intertidal_saltmarsh
RemovePrimer_Final.T1IS3_8522605005580 T1       intertidal_saltmarsh
                                       microbial_community sample
RemovePrimer_Final.T1IS1_8522605005578 prokaryote          T1IS1
RemovePrimer_Final.T1IS2_8522605005579 prokaryote          T1IS2
RemovePrimer_Final.T1IS3_8522605005580 prokaryote          T1IS3
                                       plant_species_1      plant_species_2
RemovePrimer_Final.T1IS1_8522605005578 Salicornia_tegataria Triglochin_striata
RemovePrimer_Final.T1IS2_8522605005579 Salicornia_tegataria Triglochin_striata
RemovePrimer_Final.T1IS3_8522605005580 Salicornia_tegataria Triglochin_striata
                                       blank_group
RemovePrimer_Final.T1IS1_8522605005578 Real Sample
RemovePrimer_Final.T1IS2_8522605005579 Real Sample
RemovePrimer_Final.T1IS3_8522605005580 Real Sample

In [34]:
temp_sample_data <- data.frame(sample_data(phyloseq_16S))
temp_sample_data$Read_tag <- row.names(temp_sample_data)

In [47]:
head(temp_sample_data, 3)

                                       transect habitat
RemovePrimer_Final.T1IS1_8522605005578 T1       intertidal_saltmarsh
RemovePrimer_Final.T1IS2_8522605005579 T1       intertidal_saltmarsh
RemovePrimer_Final.T1IS3_8522605005580 T1       intertidal_saltmarsh
                                       microbial_community sample
RemovePrimer_Final.T1IS1_8522605005578 prokaryote          T1IS1
RemovePrimer_Final.T1IS2_8522605005579 prokaryote          T1IS2
RemovePrimer_Final.T1IS3_8522605005580 prokaryote          T1IS3
                                       plant_species_1      plant_species_2
RemovePrimer_Final.T1IS1_8522605005578 Salicornia_tegataria Triglochin_striata
RemovePrimer_Final.T1IS2_8522605005579 Salicornia_tegataria Triglochin_striata
RemovePrimer_Final.T1IS3_8522605005580 Salicornia_tegataria Triglochin_striata
                                       blank_group
RemovePrimer_Final.T1IS1_8522605005578 Real Sample
RemovePrimer_Final.T1IS2_8522605005579 Real Sample
RemovePrimer_Final.T1IS3_8522605005580 Real Sample
                                       Read_tag
RemovePrimer_Final.T1IS1_8522605005578 RemovePrimer_Final.T1IS1_8522605005578
RemovePrimer_Final.T1IS2_8522605005579 RemovePrimer_Final.T1IS2_8522605005579
RemovePrimer_Final.T1IS3_8522605005580 RemovePrimer_Final.T1IS3_8522605005580

In [48]:
head(extraction_batches, 3)

  batch   date       assigned_date sample_id lab_blank field_blank
1 Batch_1 2026-05-07 2026-05-07    T1W1      T1L1      T1WB
2 Batch_1 2026-05-07 2026-05-07    T1W2      T1L1      T1WB
3 Batch_1 2026-05-07 2026-05-07    T1W3      T1L1      T1WB
  sequenced_tag
1 Sequenced
2 Sequenced
3 Sequenced

In [51]:
extraction_batches_all <- merge(temp_sample_data, extraction_batches, by.x = "sample", by.y = "sample_id")

In [53]:
head(extraction_batches_all, 3)

  sample transect habitat              microbial_community plant_species_1
1 T1IS1  T1       intertidal_saltmarsh prokaryote          Salicornia_tegataria
2 T1IS2  T1       intertidal_saltmarsh prokaryote          Salicornia_tegataria
3 T1IS3  T1       intertidal_saltmarsh prokaryote          Salicornia_tegataria
  plant_species_2    blank_group Read_tag                               batch
1 Triglochin_striata Real Sample RemovePrimer_Final.T1IS1_8522605005578 Batch_3
2 Triglochin_striata Real Sample RemovePrimer_Final.T1IS2_8522605005579 Batch_3
3 Triglochin_striata Real Sample RemovePrimer_Final.T1IS3_8522605005580 Batch_3
  date       assigned_date lab_blank field_blank sequenced_tag
1 2026-05-08 2026-05-08    T1ISL1    NA          Sequenced
2 2026-05-08 2026-05-08    T1ISL1    NA          Sequenced
3 2026-05-08 2026-05-08    T1ISL1    NA          Sequenced

In [19]:
# tibble::rownames_to_column(var = "Read_tag") |>
# data.frame() |>
# dplyr::mutate(tmp_sample = sample) |>
# tibble::column_to_rownames(var = "tmp_sample")

In [57]:
#head(temp_sample_data)

In [56]:
#head(extraction_batches)

In [39]:
#sample_data(phyloseq_16S) <- temp_sample_data

In [42]:
#head(temp_sample_data)

In [63]:
lapply(unique(extraction_batches$batch), function(current_batch) {
    
      extraction_batch <- extraction_batches |> dplyr::filter(batch == current_batch)
      physeq_subset <- subset_samples(physeq, sample_id %in% samples_to_keep)
        
})

[[1]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_1 2026-05-07 2026-05-07    T1W1      T1L1      T1WB        Sequenced
2 Batch_1 2026-05-07 2026-05-07    T1W2      T1L1      T1WB        Sequenced
3 Batch_1 2026-05-07 2026-05-07    T1W3      T1L1      T1WB        Sequenced

[[2]]
# A tibble: 6 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_2 2026-05-07 2026-05-07    T1SG1     T1SGL1    NA          Sequenced
2 Batch_2 2026-05-07 2026-05-07    T1SG2     T1SGL1    NA          Sequenced
3 Batch_2 2026-05-07 2026-05-07    T1SG3     T1SGL1    NA          Sequenced
4 Batch_2 2026-05-08 2026-05-07    T2SG1     T1SGL1    NA          Not_sequenced
5 Batch_2 2026-05-08 2026-05-07    T2SG2     T1SGL1    NA          Not_sequenced
6 Batch_2 2026-05-08 2026-05-07    T2SG3     T1SGL1    NA          Not_sequenced

[[3]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_4 2026-05-08 2026-05-08    T3SG1     T3SGL3    NA          Sequenced
2 Batch_4 2026-05-08 2026-05-08    T3SG2     T3SGL3    NA          Sequenced
3 Batch_4 2026-05-08 2026-05-08    T3SG3     T3SGL3    NA          Sequenced

[[4]]
# A tibble: 6 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_3 2026-05-08 2026-05-08    T1IS1     T1ISL1    NA          Sequenced
2 Batch_3 2026-05-08 2026-05-08    T1IS2     T1ISL1    NA          Sequenced
3 Batch_3 2026-05-08 2026-05-08    T1IS3     T1ISL1    NA          Sequenced
4 Batch_3 2026-05-09 2026-05-08    T2IS1     T1ISL1    NA          Not_sequenced
5 Batch_3 2026-05-09 2026-05-08    T2IS2     T1ISL1    NA          Not_sequenced
6 Batch_3 2026-05-09 2026-05-08    T2IS3     T1ISL1    NA          Not_sequenced

[[5]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_5 2026-05-09 2026-05-09    T2W1      T2L2      T2WB        Sequenced
2 Batch_5 2026-05-09 2026-05-09    T2W2      T2L2      T2WB        Sequenced
3 Batch_5 2026-05-09 2026-05-09    T2W3      T2L2      T2WB        Sequenced

[[6]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_7 2026-05-12 2026-05-12    T3IS1     T3ISL3    NA          Sequenced
2 Batch_7 2026-05-12 2026-05-12    T3IS2     T3ISL3    NA          Sequenced
3 Batch_7 2026-05-12 2026-05-12    T3IS3     T3ISL3    NA          Sequenced

[[7]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_6 2026-05-12 2026-05-12    T1SS1     T1SSL1    NA          Sequenced
2 Batch_6 2026-05-12 2026-05-12    T1SS2     T1SSL1    NA          Sequenced
3 Batch_6 2026-05-12 2026-05-12    T1SS3     T1SSL1    NA          Sequenced

[[8]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_8 2026-05-13 2026-05-13    T2SS1     T2SSL2    NA          Sequenced
2 Batch_8 2026-05-13 2026-05-13    T2SS2     T2SSL2    NA          Sequenced
3 Batch_8 2026-05-13 2026-05-13    T2SS3     T2SSL2    NA          Sequenced

[[9]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_9 2026-05-13 2026-05-13    T3SS1     T3SSL3    NA          Sequenced
2 Batch_9 2026-05-13 2026-05-13    T3SS2     T3SSL3    NA          Sequenced
3 Batch_9 2026-05-13 2026-05-13    T3SS3     T3SSL3    NA          Sequenced

[[10]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_… 2026-05-14 2026-05-14    T3W1      T3L3      T3WB        Sequenced
2 Batch_… 2026-05-14 2026-05-14    T3W2      T3L3      T3WB        Sequenced
3 Batch_… 2026-05-14 2026-05-14    T3W3      T3L3      T3WB        Sequenced

[[11]]
# A tibble: 3 × 7
  batch   date       assigned_date sample_id lab_blank field_blank sequenced_tag
  <fct>   <date>     <date>        <chr>     <chr>     <chr>       <chr>
1 Batch_… 2026-05-14 2026-05-14    T1SGB     TSGBL1    NA          Sequenced
2 Batch_… 2026-05-14 2026-05-14    T2SGB     TSGBL1    NA          Sequenced
3 Batch_… 2026-05-14 2026-05-14    T3SGB     TSGBL1    NA          Sequenced